### ISSUE TITLE
quickstart example n404

### ISSUE THREAD

**Issue by mdrio** [mariusschlegel/mlflow2prov#1]
Hi, the README mentions a quickstart example at https://github.com/mariusschlegel/mlflow2prov-quickstart-example, anyway the page is not more available. Any plan to restore the link?

**Comment by mariusschlegel** [comment]
Hi @mdrio,

Thanks for the hint. The quickstart example can be found in the directory `examples/quickstart-example/` and replaces the repository you mentioned.
